language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
install:
  - pip install -r requirements.txt
script:
  - pytest
after_success:
  - python scripts/update_version.py
  - rm dist/*
  - git add .
  - git commit -m "version update to $(cat .version) [ci skip]"
  - git push
  - python setup.py bdist_wheel
  - echo  $TWINE_USERNAME
  - twine upload -u $TWINE_USERNAME -p $TWINE_PASSWORD dist/*