language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
install:
  - pip install -r requirements.txt
script:
  - pytest
after_success:
  - rm dist/*
  - twine upload -u $TWINE_USERNAME -p $TWINE_PASSWORD dist/*